# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contacts.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ontacts.proto\x12\x08\x63ontacts\"1\n\x0bPhoneNumber\x12\x12\n\nphone_type\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\"m\n\x07\x43ontact\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12,\n\rphone_numbers\x18\x04 \x03(\x0b\x32\x15.contacts.PhoneNumberB)P\x01Z%example.com/test-protobuf/go/contactsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'contacts_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'P\001Z%example.com/test-protobuf/go/contacts'
  _PHONENUMBER._serialized_start=28
  _PHONENUMBER._serialized_end=77
  _CONTACT._serialized_start=79
  _CONTACT._serialized_end=188
# @@protoc_insertion_point(module_scope)
