// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package contacts;

public final class Contacts {
  private Contacts() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contacts_PhoneNumber_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contacts_PhoneNumber_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_contacts_Contact_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_contacts_Contact_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contacts.proto\022\010contacts\"1\n\013PhoneNumbe" +
      "r\022\022\n\nphone_type\030\001 \001(\t\022\016\n\006number\030\002 \001(\t\"m\n" +
      "\007Contact\022\r\n\005index\030\001 \001(\005\022\022\n\nfirst_name\030\002 " +
      "\001(\t\022\021\n\tlast_name\030\003 \001(\t\022,\n\rphone_numbers\030" +
      "\004 \003(\0132\025.contacts.PhoneNumberB)P\001Z%exampl" +
      "e.com/test-protobuf/go/contactsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_contacts_PhoneNumber_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_contacts_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contacts_PhoneNumber_descriptor,
        new java.lang.String[] { "PhoneType", "Number", });
    internal_static_contacts_Contact_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_contacts_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_contacts_Contact_descriptor,
        new java.lang.String[] { "Index", "FirstName", "LastName", "PhoneNumbers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
