// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package contacts;

/**
 * Protobuf type {@code contacts.Contact}
 */
public final class Contact extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:contacts.Contact)
    ContactOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Contact.newBuilder() to construct.
  private Contact(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Contact() {
    firstName_ = "";
    lastName_ = "";
    phoneNumbers_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Contact();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return contacts.Contacts.internal_static_contacts_Contact_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return contacts.Contacts.internal_static_contacts_Contact_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            contacts.Contact.class, contacts.Contact.Builder.class);
  }

  public static final int INDEX_FIELD_NUMBER = 1;
  private int index_ = 0;
  /**
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  @java.lang.Override
  public int getIndex() {
    return index_;
  }

  public static final int FIRST_NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object firstName_ = "";
  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public java.lang.String getFirstName() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      firstName_ = s;
      return s;
    }
  }
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getFirstNameBytes() {
    java.lang.Object ref = firstName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      firstName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object lastName_ = "";
  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public java.lang.String getLastName() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastName_ = s;
      return s;
    }
  }
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLastNameBytes() {
    java.lang.Object ref = lastName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PHONE_NUMBERS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<contacts.PhoneNumber> phoneNumbers_;
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  @java.lang.Override
  public java.util.List<contacts.PhoneNumber> getPhoneNumbersList() {
    return phoneNumbers_;
  }
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends contacts.PhoneNumberOrBuilder> 
      getPhoneNumbersOrBuilderList() {
    return phoneNumbers_;
  }
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  @java.lang.Override
  public int getPhoneNumbersCount() {
    return phoneNumbers_.size();
  }
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  @java.lang.Override
  public contacts.PhoneNumber getPhoneNumbers(int index) {
    return phoneNumbers_.get(index);
  }
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  @java.lang.Override
  public contacts.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
      int index) {
    return phoneNumbers_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (index_ != 0) {
      output.writeInt32(1, index_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastName_);
    }
    for (int i = 0; i < phoneNumbers_.size(); i++) {
      output.writeMessage(4, phoneNumbers_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (index_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, index_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(firstName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, firstName_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastName_);
    }
    for (int i = 0; i < phoneNumbers_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, phoneNumbers_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof contacts.Contact)) {
      return super.equals(obj);
    }
    contacts.Contact other = (contacts.Contact) obj;

    if (getIndex()
        != other.getIndex()) return false;
    if (!getFirstName()
        .equals(other.getFirstName())) return false;
    if (!getLastName()
        .equals(other.getLastName())) return false;
    if (!getPhoneNumbersList()
        .equals(other.getPhoneNumbersList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + INDEX_FIELD_NUMBER;
    hash = (53 * hash) + getIndex();
    hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getFirstName().hashCode();
    hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getLastName().hashCode();
    if (getPhoneNumbersCount() > 0) {
      hash = (37 * hash) + PHONE_NUMBERS_FIELD_NUMBER;
      hash = (53 * hash) + getPhoneNumbersList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static contacts.Contact parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static contacts.Contact parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static contacts.Contact parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static contacts.Contact parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static contacts.Contact parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static contacts.Contact parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static contacts.Contact parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static contacts.Contact parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static contacts.Contact parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static contacts.Contact parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static contacts.Contact parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static contacts.Contact parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(contacts.Contact prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code contacts.Contact}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:contacts.Contact)
      contacts.ContactOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return contacts.Contacts.internal_static_contacts_Contact_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return contacts.Contacts.internal_static_contacts_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              contacts.Contact.class, contacts.Contact.Builder.class);
    }

    // Construct using contacts.Contact.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      index_ = 0;
      firstName_ = "";
      lastName_ = "";
      if (phoneNumbersBuilder_ == null) {
        phoneNumbers_ = java.util.Collections.emptyList();
      } else {
        phoneNumbers_ = null;
        phoneNumbersBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return contacts.Contacts.internal_static_contacts_Contact_descriptor;
    }

    @java.lang.Override
    public contacts.Contact getDefaultInstanceForType() {
      return contacts.Contact.getDefaultInstance();
    }

    @java.lang.Override
    public contacts.Contact build() {
      contacts.Contact result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public contacts.Contact buildPartial() {
      contacts.Contact result = new contacts.Contact(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(contacts.Contact result) {
      if (phoneNumbersBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          phoneNumbers_ = java.util.Collections.unmodifiableList(phoneNumbers_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.phoneNumbers_ = phoneNumbers_;
      } else {
        result.phoneNumbers_ = phoneNumbersBuilder_.build();
      }
    }

    private void buildPartial0(contacts.Contact result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.index_ = index_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.firstName_ = firstName_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.lastName_ = lastName_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof contacts.Contact) {
        return mergeFrom((contacts.Contact)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(contacts.Contact other) {
      if (other == contacts.Contact.getDefaultInstance()) return this;
      if (other.getIndex() != 0) {
        setIndex(other.getIndex());
      }
      if (!other.getFirstName().isEmpty()) {
        firstName_ = other.firstName_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getLastName().isEmpty()) {
        lastName_ = other.lastName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (phoneNumbersBuilder_ == null) {
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbers_.isEmpty()) {
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensurePhoneNumbersIsMutable();
            phoneNumbers_.addAll(other.phoneNumbers_);
          }
          onChanged();
        }
      } else {
        if (!other.phoneNumbers_.isEmpty()) {
          if (phoneNumbersBuilder_.isEmpty()) {
            phoneNumbersBuilder_.dispose();
            phoneNumbersBuilder_ = null;
            phoneNumbers_ = other.phoneNumbers_;
            bitField0_ = (bitField0_ & ~0x00000008);
            phoneNumbersBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPhoneNumbersFieldBuilder() : null;
          } else {
            phoneNumbersBuilder_.addAllMessages(other.phoneNumbers_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              index_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              firstName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              lastName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              contacts.PhoneNumber m =
                  input.readMessage(
                      contacts.PhoneNumber.parser(),
                      extensionRegistry);
              if (phoneNumbersBuilder_ == null) {
                ensurePhoneNumbersIsMutable();
                phoneNumbers_.add(m);
              } else {
                phoneNumbersBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int index_ ;
    /**
     * <code>int32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }
    /**
     * <code>int32 index = 1;</code>
     * @param value The index to set.
     * @return This builder for chaining.
     */
    public Builder setIndex(int value) {
      
      index_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int32 index = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearIndex() {
      bitField0_ = (bitField0_ & ~0x00000001);
      index_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object firstName_ = "";
    /**
     * <code>string first_name = 2;</code>
     * @return The firstName.
     */
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @return The bytes for firstName.
     */
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string first_name = 2;</code>
     * @param value The firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      firstName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string first_name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFirstName() {
      firstName_ = getDefaultInstance().getFirstName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string first_name = 2;</code>
     * @param value The bytes for firstName to set.
     * @return This builder for chaining.
     */
    public Builder setFirstNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      firstName_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object lastName_ = "";
    /**
     * <code>string last_name = 3;</code>
     * @return The lastName.
     */
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @return The bytes for lastName.
     */
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string last_name = 3;</code>
     * @param value The lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      lastName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string last_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearLastName() {
      lastName_ = getDefaultInstance().getLastName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string last_name = 3;</code>
     * @param value The bytes for lastName to set.
     * @return This builder for chaining.
     */
    public Builder setLastNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      lastName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<contacts.PhoneNumber> phoneNumbers_ =
      java.util.Collections.emptyList();
    private void ensurePhoneNumbersIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        phoneNumbers_ = new java.util.ArrayList<contacts.PhoneNumber>(phoneNumbers_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        contacts.PhoneNumber, contacts.PhoneNumber.Builder, contacts.PhoneNumberOrBuilder> phoneNumbersBuilder_;

    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public java.util.List<contacts.PhoneNumber> getPhoneNumbersList() {
      if (phoneNumbersBuilder_ == null) {
        return java.util.Collections.unmodifiableList(phoneNumbers_);
      } else {
        return phoneNumbersBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public int getPhoneNumbersCount() {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.size();
      } else {
        return phoneNumbersBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public contacts.PhoneNumber getPhoneNumbers(int index) {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.get(index);
      } else {
        return phoneNumbersBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder setPhoneNumbers(
        int index, contacts.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, value);
        onChanged();
      } else {
        phoneNumbersBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder setPhoneNumbers(
        int index, contacts.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.set(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder addPhoneNumbers(contacts.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(value);
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder addPhoneNumbers(
        int index, contacts.PhoneNumber value) {
      if (phoneNumbersBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(index, value);
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder addPhoneNumbers(
        contacts.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder addPhoneNumbers(
        int index, contacts.PhoneNumber.Builder builderForValue) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.add(index, builderForValue.build());
        onChanged();
      } else {
        phoneNumbersBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder addAllPhoneNumbers(
        java.lang.Iterable<? extends contacts.PhoneNumber> values) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, phoneNumbers_);
        onChanged();
      } else {
        phoneNumbersBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder clearPhoneNumbers() {
      if (phoneNumbersBuilder_ == null) {
        phoneNumbers_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        phoneNumbersBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public Builder removePhoneNumbers(int index) {
      if (phoneNumbersBuilder_ == null) {
        ensurePhoneNumbersIsMutable();
        phoneNumbers_.remove(index);
        onChanged();
      } else {
        phoneNumbersBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public contacts.PhoneNumber.Builder getPhoneNumbersBuilder(
        int index) {
      return getPhoneNumbersFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public contacts.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
        int index) {
      if (phoneNumbersBuilder_ == null) {
        return phoneNumbers_.get(index);  } else {
        return phoneNumbersBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public java.util.List<? extends contacts.PhoneNumberOrBuilder> 
         getPhoneNumbersOrBuilderList() {
      if (phoneNumbersBuilder_ != null) {
        return phoneNumbersBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(phoneNumbers_);
      }
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public contacts.PhoneNumber.Builder addPhoneNumbersBuilder() {
      return getPhoneNumbersFieldBuilder().addBuilder(
          contacts.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public contacts.PhoneNumber.Builder addPhoneNumbersBuilder(
        int index) {
      return getPhoneNumbersFieldBuilder().addBuilder(
          index, contacts.PhoneNumber.getDefaultInstance());
    }
    /**
     * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
     */
    public java.util.List<contacts.PhoneNumber.Builder> 
         getPhoneNumbersBuilderList() {
      return getPhoneNumbersFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        contacts.PhoneNumber, contacts.PhoneNumber.Builder, contacts.PhoneNumberOrBuilder> 
        getPhoneNumbersFieldBuilder() {
      if (phoneNumbersBuilder_ == null) {
        phoneNumbersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            contacts.PhoneNumber, contacts.PhoneNumber.Builder, contacts.PhoneNumberOrBuilder>(
                phoneNumbers_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        phoneNumbers_ = null;
      }
      return phoneNumbersBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:contacts.Contact)
  }

  // @@protoc_insertion_point(class_scope:contacts.Contact)
  private static final contacts.Contact DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new contacts.Contact();
  }

  public static contacts.Contact getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Contact>
      PARSER = new com.google.protobuf.AbstractParser<Contact>() {
    @java.lang.Override
    public Contact parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Contact> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Contact> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public contacts.Contact getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

