// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package contacts;

public interface ContactOrBuilder extends
    // @@protoc_insertion_point(interface_extends:contacts.Contact)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 index = 1;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string last_name = 3;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 3;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  java.util.List<contacts.PhoneNumber> 
      getPhoneNumbersList();
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  contacts.PhoneNumber getPhoneNumbers(int index);
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  int getPhoneNumbersCount();
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  java.util.List<? extends contacts.PhoneNumberOrBuilder> 
      getPhoneNumbersOrBuilderList();
  /**
   * <code>repeated .contacts.PhoneNumber phone_numbers = 4;</code>
   */
  contacts.PhoneNumberOrBuilder getPhoneNumbersOrBuilder(
      int index);
}
