// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package contacts;

public interface PhoneNumberOrBuilder extends
    // @@protoc_insertion_point(interface_extends:contacts.PhoneNumber)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string phone_type = 1;</code>
   * @return The phoneType.
   */
  java.lang.String getPhoneType();
  /**
   * <code>string phone_type = 1;</code>
   * @return The bytes for phoneType.
   */
  com.google.protobuf.ByteString
      getPhoneTypeBytes();

  /**
   * <code>string number = 2;</code>
   * @return The number.
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 2;</code>
   * @return The bytes for number.
   */
  com.google.protobuf.ByteString
      getNumberBytes();
}
